name: Cypress E2E Tests

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary
  pull_request:
    branches:
      - main  # Adjust the branch name if necessary
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: install webpack
        run: npm install --save-dev webpack webpack-cli webpack-dev-server

      - name: Run Cypress tests
        run: npm run cypress:test
